on:
  pull_request:
    branches:
      - main

name: Build check

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v10

      - name: Install Python, packages and Quarto from uv.lock
        run: uv sync --locked

      - name: Render the web version
        run: uv run quarto render --to html
