on: pull_request
name: Temporary PDF check
permissions:
  contents: read
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v10.3.0
      - run: |
          uv sync --locked
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"
      - run: quarto install tinytex --no-prompt
      - run: which quarto && quarto --version && quarto render
      - run: ls -la _book/*.pdf
